export const ChallengeTypes = {
    GET_CHALLENGE: 'GET_CHALLENGE',
    GET_CONTEXT_CHALLENGES: 'GET_CONTEXT_CHALLENGES',
    REGISTER_CHALLENGE: 'REGISTER_CHALLENGE',
    UPDATE_CHALLENGE: 'UPDATE_CHALLENGE',
    DELETE_CHALLENGE: 'DELETE_CHALLENGE',
    CHALLENGE_SUCCESS: 'CHALLENGE_SUCCESS',
    CHALLENGE_FAIL: 'CHALLENGE_FAIL'
}