export const ContextTypes = {
    GET_CONTEXT: 'GET_CONTEXT',
    REGISTER_CONTEXT: 'REGISTER_CONTEXT',
    UPDATE_CONTEXT: 'UPDATE_CONTEXT',
    DELETE_CONTEXT: 'DELETE_CONTEXT',
    CONTEXT_SUCCESS: 'CONTEXT_SUCCESS',
    CONTEXT_FAIL: 'CONTEXT_FAIL'
}